title: "RSpecで学ぶテストの考え方"
summary: "RSpecを用いて、テストに関する以下の考え方を学びます。\n
（現時点では書きかけです）

- テストコードをなぜ書く必要があるのか？ \n
- テストするための基本的な考え方 \n
\n
[対象読者]\n
RSpec•自動テスト初学者\n
(前半はRspecを知らなくても問題ない内容です。)"
topics: ["Ruby", "RSpec", "初心者向け", "テスト", "Rails"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - chapter1 # チャプター1
  - chapter2 # チャプター2
  - chapter3 # チャプター3
